package xml;

import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;


import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class TesteXml {


    public static void main(String[] args) throws IOException, ParserConfigurationException, SAXException {


        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        System.out.println (df.format (new Date()));


      //  InputStream inputStream= new FileInputStream(styleSheet);
       // StringBufferInputStream stringBufferInputStream = new StringBufferInputStream(styleSheet);
        ByteArrayInputStream    byteArrayInputStream =  new ByteArrayInputStream(styleSheet.getBytes(StandardCharsets.UTF_8));
      //  ByteArrayInputStream    byteArrayInputStream =  new ByteArrayInputStream(styleSheet);

        System.out.println(byteArrayInputStream.toString());


        Reader reader = new InputStreamReader(byteArrayInputStream ,"UTF-8");
        InputSource is = new InputSource(reader);
        is.setEncoding("UTF-8");

       // DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
       // DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
       // Document doc = dBuilder.parse(is);



        DocumentBuilder dBuilder2 =  DocumentBuilderFactory.newInstance().newDocumentBuilder();
        Document doc2 = dBuilder2.parse(is);

        System.out.println(doc2);

    }

    static String  styleSheet ="<html> "
            +"<head> "
            +"    <title>Atendimento</title> "
            +"    <style type='text/css'> "
            +"       @page { "
            +"           size: A4; "
            +"            @bottom-center { "
            +"                content: element(footer);"
            +"                vertical-align: top;"
            +"            }"
            +""
            +"           @top-center {"
            +"                content: element(header);"
            +"                vertical-align: bottom;"
            +"            }"
            +""
            +"            margin-top: 7.9cm;"
            +"            margin-bottom:2.29cm;"
            +"       }"
            +""
            +"       .header {"
            +"           display: block;"
            +"           position: running(header);"
            +"           text-align: center;"
            +"           font-size: 25px;"
            +"           font-family: Arial, sans-serif;"
            +"           *"
            +"      }"
            +""
            +"       .footer {"
            +"           width: 100%;"
            +"           height: 100%;"
            +"           font-size: 12px;"
            +"           margin-left: auto;"
            +"          margin-right: auto;"
            +"           display: block;"
            +"          position: running(footer);"
            +"          font-family: Arial, sans-serif;"
            +"      }"
            +""
            +"       #pagenumber:before {"
            +"         content: counter(page);"
            +"     }"
            +""
            +"       #pagecount:before {"
            +"          content: counter(pages);"
            +"     }"
            +""
            +"       body {"
            +"          margin: 0px;"
            +"     }"
            +""
            +"       .sheet {"
            +"           margin: 0;"
            +"          height: auto;"
            +"      }"
            +""
            +"       @media screen {"
            +"          body {"
            +"             background: #e0e0e0;"
            +"            width: 210mm;"
            +"       }"
            +""
            +"          .sheet {"
            +"             background: white;"
            +"            box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);"
            +"          margin: 3mm;"
            +"         border: 1px solid #000;"
            +"       }"
            +"  }"
            +""
            +"       .table-titulo {"
            +"           width: 100%;"
            +"          border: 1px solid #000;"
            +"          margin-left: auto;"
            +"          margin-right: auto;"
            +"     }"
            +""
            +"     .table-info-atend {"
            +"          width: 100%;"
            +"         border-left: 1px solid #000;"
            +"         border-right: 1px solid #000;"
            +"         border-bottom: 1px solid #000;"
            +"         border-spacing: 0;"
            +"    }"
            +""
            +"      .table-valores {"
            +"          width: 100%;"
            +"          border-left: 1px solid #000;"
            +"         border-right: 1px solid #000;"
            +"     }"
            +""
            +"       .title_result {"
            +"         background: #d3d3d3;"
            +"       width: 210px;"
            +"           text-align: right;"
            +"           font-size: 12px;"
            +"           font-weight: bold;"
            +"           font-family: Arial, sans-serif;"
            +"          border-collapse: collapse;"
            +"          padding-right: 5px;"
            +"          border-right: 1px solid #000;"
            +"          border-bottom: 1px solid #000;"
            +"      }"
            +""
            +"      .result_element {"
            +"        font-family: Arial, sans-serif;"
            +"      font-size: 12px;"
            +"    white-space: pre-line;"
            +"  padding-left: 5px;"
            +"      text-align: left;"
            +"      width: 530px;"
            +"       border-bottom: 1px solid #000;"
            +"   }"
            +"    .table-footer {"
            +"        width: 100%;"
            +"        height: 15px;"
            +"        border-left: 1px solid #000;"
            +"        border-right: 1px solid #000;"
            +"        border-bottom: 1px solid #000;"
            +"    }"
            +""
            +"     .title {"
            +"         background: #d3d3d3;"
            +"        width: 80px;"
            +"         text-align: left;"
            +"         font-size: 12px;"
            +"         font-family: Arial, sans-serif;"
            +"         padding: 0;"
            +"         margin: 0;"
            +"         border-collapse: collapse;"
            +"     }"
            +""
            +"      .result {"
            +"        width: 200px;"
            +"        text-align: left;"
            +"        font-size: 12px;"
            +"        font-family: Arial, sans-serif;"
            +"         padding: 0;"
            +"         padding-left: 5px;"
            +"         margin: 0;"
            +"        border-collapse: collapse;"
            +"    }"
            +""
            +"      .codigodebarras {"
            +"        display: flex;"
            +"        flex-direction: column;"
            +"       justify-content: center;"
            +"       align-items: center;"
            +"   }"
            +""
            +"      .codigodebarras label {"
            +"      font-size: 10px;"
            +"        font-weight: bold;"
            +"        margin: 0;"
            +"   }"
            +""
            +"      .dataIdade {"
            +"         margin-right: 0.2em; "
            +"    }"
            +""
            +"      table {"
            +"        page-break-inside: auto;"
            +"       border-spacing: 0;"
            +"   }"
            +""
            +"       tr {"
            +"         page-break-inside: avoid;"
            +"        page-break-after: auto;"
            +"    }"
            +""
            +"      .retangulo {"
            +"        width: 260px;"
            +"        height: 15px;"
            +"        border: 1px ridge rgb(54, 54, 54);"
            +"        font-size: 8px;"
            +"       text-align: center;"
            +"       font-family: Arial, sans-serif;"
            +"    }"
            +""
            +"      .codigo-barras {"
            +"          font-family: codigo128;"
            +"          font-size: 38px;"
            +"          text-align: center;"
            +"         margin: 0;"
            +"     }"
            +""
            +"      .codigo-barras-title {"
            +"         margin: 0;"
            +"         text-align: center;"
            +"         font-size: 12px;"
            +"     }"
            +""
            +"      .titulo {"
            +"         font-family: Arial, sans-serif;"
            +"          font-size: 30px;"
            +"          font-weight: bold;"
            +"     }"
            +""
            +"       .usu_ad {"
            +"          width: 100%;"
            +"          height: 15px;"
            +"          text-align: right;"
            +"     }"
            +"  </style>"
            +"</head>"
            +""
            +"<body>"
            +"    <section class='sheet'>"
            +"        <div class='header'>"
            +"            <table class='table-titulo' cellpadding='0'>"
            +"                <tr>"
            +"                    <td colspan='3'>"
            +"                        <div>"
            +"                            <p class='titulo'>"
            +"                                campo_1@"
            +"                            </p>"
            +"                        </div>"
            +"                    </td>"
            +"                </tr>"
            +"                <tr>"
            +"                   <td width='520px'>"
            +"                   </td> ç"
            +"                   <td colspan='1' class='retangulo'>"
            +"                       <p style='margin-bottom: 0px;'><b>campo_2@</b></p>"
            +"                       <p style='margin-top: 0px;'>campo_3@</p>"
            +"                   </td>"
            +"                   <td width='10px'>"
            +"                   </td>"
            +"               </tr>"
            +"               <tr>"
            +"                   <td height='5px'>"
            +"                   </td>"
            +"                </tr>"
            +"            </table>"
            +"            <table class='table-info-atend'>"
            +"                <tr>"
            +"                    <td>"
            +"                        <table width='100%'>"
            +"                            <tr>"
            +"                               <td>"
            +"                                   <table>"
            +"                                       <tr>"
            +"                                           <td class='title'>"
            +"                                              Paciente:"
            +"                                           </td>"
            +"                                          <td class='result'>"
            +"                                               campo_5@"
            +"                                          </td>"
            +"                                      </tr>"
            +"                                   </table>"
            +"                              </td>"
            +"                              <td>"
            +"                                  <table>"
            +"                                      <tr>"
            +"                                          <td class='title'>"
            +"                                              Atendimento:"
            +"                                          </td>"
            +"                                          <td class='result'>"
            +"                                             campo_6@"
            +"                                          </td>"
            +"                                      </tr>"
            +"                                  </table>"
            +"                              </td>"
            +"                         </tr>"
            +"                         <tr>"
            +"                             <td>"
            +"                                 <table>"
            +"                                     <tr>"
            +"                                         <td class='title'>"
            +"                                             Data Nascto:"
            +"                                         </td>"
            +"                                         <td class='result'>"
            +"                                             campo_7@"
            +"                                         </td>"
            +"                                     </tr>"
            +"                                 </table>"
            +"                             </td>"
            +"                             <td>"
            +"                                 <table>"
            +"                                     <tr>"
            +"                                         <td class='title'>"
            +"                                             Convnio:"
            +"                                         </td>"
            +"                                         <td class='result'>"
            +"                                             campo_9@"
            +"                                         </td>"
            +"                                     </tr>"
            +"                                 </table>"
            +"                             </td>"
            +"                            <td>"
            +"                             </td>"
            +"                         </tr>"
            +"                          <tr>"
            +"                              <td>"
            +"                                  <table>"
            +"                                      <tr>"
            +"                                          <td class='title'>"
            +"                                              Setor/Unid:"
            +"                                          </td>"
            +"                                         <td class='result'>"
            +"                                             campo_10@"
            +"                                         </td>"
            +"                                     </tr>"
            +"                                 </table>"
            +"                             </td>"
            +"                             <td>"
            +"                                 <table>"
            +"                                     <tr>"
            +"                                         <td class='title'>"
            +"                                             Profissional:"
            +"                                         </td>"
            +"                                         <td class='result'>"
            +"                                             campo_11@"
            +"                                         </td>"
            +"                                     </tr>"
            +"                                 </table>"
            +"                             </td>"
            +"                         </tr>"
            +"                         <tr>"
            +"                             <td>"
            +"                                 <table>"
            +"                                     <tr>"
            +"                                          <td class='title'>"
            +"                                             Dt Registro:"
            +"                                         </td>"
            +"                                         <td class='result'>"
            +"                                             campo_12@"
            +"                                         </td>"
            +"                                     </tr>"
            +"                                 </table>"
            +"                             </td>"
            +"                         </tr>"
            +"                     </table>"
            +"                 </td>"
            +"                 <td>"
            +"                     <table>"
            +"                         <tr>"
            +"                             <td>"
            +"                                 <p class='codigo-barras-title'>N Pronturio</p>"
            +"                                 <p class='codigo-barras'>campo_4@</p>"
            +"                                  <p class='codigo-barras-title'>campo_4@</p>"
            +"                             </td>"
            +"                         </tr>"
            +"                     </table>"
            +"                 </td>"
            +"             </tr>"
            +"         </table>"
            +"     </div>"
            +"     <div class='footer'>"
            +"        <table class='table-footer'>"
            +"             <tr>"
            +"                 <td style='width: 350px;padding-left: 5px'>"
            +"                    <p> Impresso em: campo_14@</p>"
            +"                </td>"
            +"                <td>"
            +"                    <p>Pagina <span id='pagenumber'></span></p>"
            +"                </td>"
            +"                <td>"
            +"                    <p>USUARIO@</p>"
            +"                </td>"
            +"                <td>"
            +"                    <p>CATE00122</p>"
            +"                </td>"
            +"            </tr>"
            +"        </table>"
            +"        <table class='usu_ad'>"
            +"             <tr>"
            +"                <td>"
            +"                    <p>USUARIO_AD@</p>"
            +"                </td>"
            +"            </tr>"
            +"        </table>"
            +"    </div>"
            +""
            +"    <div>"
            +"        <div>"
            +"            <table class='table-valores'>"
            +"                   campo_13@"
            +"           </table>"
            +"        </div>"
            +" "
            +"       </div> "
            +"  </section>"
            +"</body> "
            +"</html>";



}
